import { Inter } from '@next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'
import Nav from '../comps/nav/Nav'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [show, setShow] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {show && <div className="dropdwon_blur_layer"></div>}
      <Nav show={show} setShow={setShow} />
      <main className={styles.main}>

      </main>
    </>
  )
}
